model_class: MathLLMModel
model_name: "Qwen/Qwen2.5-Math-7B-Instruct"
do_sample: false
temperature: null
max_new_tokens: 256
system_prompt: "qwen_math"
search_reversed: false
quantization:
  load_in_4bit: true
  quant_type: "nf4"
  compute_dtype: "bfloat16"
  double_quant: true
use_retrieval: false
use_dense_retrieval: true
use_code_executor: true
use_router: false
log_dir: "AgenticAI_scripts"
